// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BasicTable: typeof import('./src/components/basic-table/index.vue')['default']
    EditForm: typeof import('./src/components/form/EditForm.vue')['default']
    EditTable: typeof import('./src/components/basic-table/EditTable.vue')['default']
    ExpandToggle: typeof import('./src/components/form/ExpandToggle.vue')['default']
    FilterSearch: typeof import('./src/components/form/FilterSearch.vue')['default']
    FormList: typeof import('./src/components/form/FormList.vue')['default']
    Identify: typeof import('./src/components/Identify/index.vue')['default']
    RouteContent: typeof import('./src/components/RouteContent/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowWrapper: typeof import('./src/components/row-layout/RowWrapper.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Widgets: typeof import('./src/components/form/widgets/index.vue')['default']
    WithArrowScroll: typeof import('./src/components/with-arrow-scroll/index.vue')['default']
  }
}
