export { default as Menu } from './Menu/index.vue'
export { default as Header } from './header/index.vue'
export { default as Title } from './title/index.vue'
export { default as View } from './view/index.vue'
export { default as TagsView } from './tags-view/index.vue'
